### ISSUE TITLE
Question: Encrypt a unencrypted Database

### ISSUE THREAD

**Issue by jochumdev** [zopefoundation/cipher.encryptingstorage#2]
Is there a simple way to completely encrypt a decrypted Database?

So, having a database that isn't using cipher.encryptingstorage then use cipher.encryptingstorage and 
encrypt all contents.

@mgedmin @jimfulton @frisi

**Comment by jimfulton** [comment]
I'm not familiar with cipher.encryptingstorage, but if it works with ZRS, then you could replicate from the unencrypted database to the encrypted one.

**Comment by jamadden** [comment]
relstorage also [includes a general-purpose tool](https://pypi.python.org/pypi/RelStorage#zodbconvert) for copying all the data from one database storage to another. I've used it to take an uncompressed database and compress it with zc.zlibstorage. If you can write the source and destination storages in ZConfig syntax, then zodbconvert should work with them.

**Comment by jochumdev** [comment]
@jamadden thank your for the link to zodbconvert i did what i want after a little patch to cipher.encryptingstorage.
